### PR TITLE
Implement package model class

### PR DESCRIPTION
**Pull request by simonpcouch**
This PR starts laying the groundwork for the package to be able to make use of rsample (for LOO CV) and other tidymodels functionality.

The idea is to structure these models like other model types—instead of custom function names for carrying out common modeling operations, like fitting and predicting, we add a class onto the model “object” and then define methods, like `fit()` and `predict()`, for that class. We’re defining our own analogue of the output of `lm`, for example. I call the class `fe_bayes_lr` for the model (subclassing `list`) and `fe_data` for the data (subclassing `tbl_df`).

I left the internals of the fitting and predicting functionality alone as much as possible, except restructuring the inputs/outputs to align with tidy modeling principles. More on that [here](https://tidymodels.github.io/model-implementation-principles/).

The next step here will be to minimally define what the input data (`focal_vs_comp` in most cases, from what I can tell) needs to look like to be able to fit these models so we can class that as well. That class will be a subclass of `tbl_df` and just specify things like what columns need to be present and possibly a few attributes. Pointers on what “valid” input data looks like would be much appreciated—it looks like `create_focal_vs_comp()` and `create_bayesian_model_data()` get us some of the way there. :-) In the meantime, I alias the fit and predict methods with a `*.tbl_df` method that just dispatches to `fit.fe_data`, `predict.fe_bayes_lr`.

The majority of the files changed here just rename the `fit_bayesian_model` and `predict_bayesian_model` functions to `fit` and `predict` and adjust code to accommodate changes in output types for the two methods. `model_functions.R`, `utils.R`, and `constructors.R` contain most of the major changes. I leave the manuscript and example data alone for the most part, as the API will continue changing a good bit with these next few PRs. I did adjust examples for helper functions so they would still run successfully—the interface looks a bit clunky for now, and will clean up once we've clarified input structure.

The directions I have in mind for coming PRs:

* specifying the structure of input data + adding a class
* align plotting functions with `autoplot` conventions
* add print methods for `fe_data` and `fe_bayes_lr` objects
* unit testing
* code cleanup + revising documentation

### CODE REVIEW

**Comment by rudeboybert** [comment]
In preparation for our meeting today I'm writing out in detail what `focal_vs_comp` objects are intended to capture. Note: I'm writing it out in extra detail so that it can serve as an MVP for the eventual manuscript text.

Referring to the "competitor species ID matters" viz I showed previously:
- A "focal tree" is a tree of interest (the red dot at the center of the viz)
- Each focal tree has a certain set of "competitor trees" (the other dots within a 7.5m radius of it). The idea is every tree in the forest gets a turn at being a "focal tree"

focal_vs_comp

The example in the README illustrates the concept:
```
> focal_vs_comp_ex
# A tibble: 11 x 10
   focal_ID focal_sp         dbh foldID    geometry growth comp_ID  dist comp_sp        comp_basal_area
      <dbl> <fct>          <dbl> <fct>      <POINT>  <dbl>   <dbl> <dbl> <fct>                    <dbl>
 1        2 american_beech    20 1        (1.5 2.5)  0.800       1 0.75  sugar_maple            0.00196
 2        2 american_beech    20 1        (1.5 2.5)  0.800       3 0.354 sugar_maple            0.0177 
 3        3 sugar_maple       15 1      (1.75 2.25)  1.00        2 0.354 american_beech         0.0314 
 4        4 american_beech    12 1          (3 1.5)  0.400       5 0.354 sugar_maple            0.0962 
 5        5 sugar_maple       35 1      (3.25 1.75)  1.40        4 0.354 american_beech         0.0113 
 6        7 sugar_maple       22 2          (8 1.5)  0.600       8 0.901 american_beech         0.0154 
 7        7 sugar_maple       22 2          (8 1.5)  0.600       9 0.75  sugar_maple            0.139  
 8        7 sugar_maple       22 2          (8 1.5)  0.600      10 0.791 american_beech         0.00126
 9        9 sugar_maple       42 2       (8.75 1.5)  1.40        7 0.75  sugar_maple            0.0380 
10        9 sugar_maple       42 2       (8.75 1.5)  1.40        8 0.791 american_beech         0.0154 
11        9 sugar_maple       42 2       (8.75 1.5)  1.40       10 0.25  american_beech         0.00126
```

We have columns presenting info on:
- rows representing every instance of a competitor tree. For ex: the first two rows represent both competitors for a single focal tree. 
- variables pertaining to the focal tree `focal_ID` thru `growth`: tree tag number `focal_ID`; geospatial info `geometry` & `foldID`; the outcome variable y `growth`; x covariates pertaining to the focal tree `species` (but we could also include others like `leaf_density` etc)
- variables pertaining to its competitor trees `comp_ID` thru `comp_basal_area`: tree tag number `comp_ID`; geospatial info `dist` to focal tree; x covariates pertaining to competitor tree `comp_basal_area`

You can see there is a lot of redundancy, given that the same focal tree has multiple competitors. That's why I'm thinking a [list-column](https://rstudio.com/resources/webinars/how-to-work-with-list-columns/) data format would be appropriate. 

list_column

**Comment by simonpcouch** [comment]
Feel free to ignore until our meeting -- thinking through what a proper interface might look like. :-)

``` r
library(tidyverse)
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.3.9000     ✓ recipes   0.1.15    
#> ✓ dials     0.0.9.9000     ✓ rsample   0.0.8.9000
#> ✓ infer     0.5.4.9000     ✓ tune      0.1.2     
#> ✓ modeldata 0.1.0          ✓ workflows 0.2.1.9000
#> ✓ parsnip   0.1.4.9000     ✓ yardstick 0.0.7
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x scales::discard() masks purrr::discard()
#> x dplyr::filter()   masks stats::filter()
#> x recipes::fixed()  masks stringr::fixed()
#> x dplyr::lag()      masks stats::lag()
#> x yardstick::spec() masks readr::spec()
#> x recipes::step()   masks stats::step()
  
# "Base" style modeling ------------------------------------------

# typical interface 
if (FALSE) {
mod <-
  model_type(
    formula,
    data,
    parameters
  ) %>%

mod %>% 
  predict(data)
}
  
# example - lm
mod <- 
  lm(
    mpg ~ wt + cyl,
    mtcars
  )

class(mod)
#> [1] "lm"

mod
#> 
#> Call:
#> lm(formula = mpg ~ wt + cyl, data = mtcars)
#> 
#> Coefficients:
#> (Intercept)           wt          cyl  
#>      39.686       -3.191       -1.508

mod %>% predict(mtcars)
#>           Mazda RX4       Mazda RX4 Wag          Datsun 710      Hornet 4 Drive 
#>            22.27914            21.46545            26.25203            20.38052 
#>   Hornet Sportabout             Valiant          Duster 360           Merc 240D 
#>            16.64696            19.59873            16.23213            23.47588 
#>            Merc 230            Merc 280           Merc 280C          Merc 450SE 
#>            23.60352            19.66255            19.66255            14.63665 
#>          Merc 450SL         Merc 450SLC  Cadillac Fleetwood Lincoln Continental 
#>            15.72158            15.56203            10.87130            10.31607 
#>   Chrysler Imperial            Fiat 128         Honda Civic      Toyota Corolla 
#>            10.56816            26.63494            28.50166            27.79965 
#>       Toyota Corona    Dodge Challenger         AMC Javelin          Camaro Z28 
#>            25.78934            16.39168            16.66291            15.37057 
#>    Pontiac Firebird           Fiat X1-9       Porsche 914-2        Lotus Europa 
#>            15.35461            27.48055            26.82640            28.82714 
#>      Ford Pantera L        Ferrari Dino       Maserati Bora          Volvo 142E 
#>            17.50852            21.80050            16.23213            24.78418

# possible interface for forestecology
if (FALSE) {
  dat <-
    raw_data %>%
    data_preparation_functions()
  
  mod <-
    bayes_lm(
      # is formula implied from the data?,
      dat,
      priors
    )
  
  mod %>%
    predict(dat)
}

# Translation to tidymodels -------------------------------------------------

# typical interface
if (FALSE) {
  mod <-
    model_type(
      parameters
    ) %>%
    set_engine("engine") %>%
    set_mode("mode") %>%
    fit(
      formula,
      data
    )
}

# example - lm
mod <- 
  linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression") %>%
  fit(
    mpg ~ wt + cyl,
    mtcars
  )

mod
#> parsnip model object
#> 
#> Fit time:  2ms 
#> 
#> Call:
#> stats::lm(formula = mpg ~ wt + cyl, data = data)
#> 
#> Coefficients:
#> (Intercept)           wt          cyl  
#>      39.686       -3.191       -1.508

class(mod)
#> [1] "_lm"       "model_fit"

mod %>% predict(mtcars)
#> # A tibble: 32 x 1
#>    .pred
#>    <dbl>
#>  1  22.3
#>  2  21.5
#>  3  26.3
#>  4  20.4
#>  5  16.6
#>  6  19.6
#>  7  16.2
#>  8  23.5
#>  9  23.6
#> 10  19.7
#> # … with 22 more rows

# possible interface for forestecology
if (FALSE) {
  dat <-
    raw_data %>%
    data_preparation_functions()
  
  mod <-
    linear_reg() %>%
    # I haven't seen folks implement new engines for existing
    # model types before, though this seems like it ought to be
    # the proper way to do this. Will check in with Max on this.
    set_engine("forestecology") %>%
    set_mode("regression") %>%
    # mode is implied
    fit(
      data
    )
  
  mod %>%
    predict()
}
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by rudeboybert** [comment]
Hey @simonpcouch, thanks again for putting up with my scattered explanation of the actual model itself. Given that this whole “focal versus competitor” tree idea forms the crux of the science behind our model, it’s worth amplifying a little bit. Going back to the `focal_vs_comp_ex` example above: 

```
> focal_vs_comp_ex
# A tibble: 11 x 10
   focal_ID focal_sp         dbh foldID    geometry growth comp_ID  dist comp_sp        comp_basal_area
      <dbl> <fct>          <dbl> <fct>      <POINT>  <dbl>   <dbl> <dbl> <fct>                    <dbl>
 1        2 american_beech    20 1        (1.5 2.5)  0.800       1 0.75  sugar_maple            0.00196
 2        2 american_beech    20 1        (1.5 2.5)  0.800       3 0.354 sugar_maple            0.0177 
 3        3 sugar_maple       15 1      (1.75 2.25)  1.00        2 0.354 american_beech         0.0314 
 4        4 american_beech    12 1          (3 1.5)  0.400       5 0.354 sugar_maple            0.0962 
 5        5 sugar_maple       35 1      (3.25 1.75)  1.40        4 0.354 american_beech         0.0113 
 6        7 sugar_maple       22 2          (8 1.5)  0.600       8 0.901 american_beech         0.0154 
 7        7 sugar_maple       22 2          (8 1.5)  0.600       9 0.75  sugar_maple            0.139  
 8        7 sugar_maple       22 2          (8 1.5)  0.600      10 0.791 american_beech         0.00126
 9        9 sugar_maple       42 2       (8.75 1.5)  1.40        7 0.75  sugar_maple            0.0380 
10        9 sugar_maple       42 2       (8.75 1.5)  1.40        8 0.791 american_beech         0.0154 
11        9 sugar_maple       42 2       (8.75 1.5)  1.40       10 0.25  american_beech         0.00126
```

the actual `lm` formula we would actually fit is (braces used only for organization):

`growth ~ {covariates relating to focal tree} + {covariates relating to competitor trees}`
`growth ~ {focal_sp + dbh + dbh * focal_sp} + {american_beech_comp_basal_area * focal_sp + sugar_maple_comp_basal_area * focal_sp}`

where`american_beech_comp_basal_area` is for a given focal tree the sum of `comp_basal_area` for all `american_beech` competitor trees. The idea being the "amount of competition" felt by a focal tree is the sum of sizes of its competitors.  So for example, taking the focal tree with `focal_ID` = 9 above (last 3 rows),

- `american_beech_comp_basal_area` = 0.0154 + 0.00126
- `sugar_maple_comp_basal_area` = 0.0380

For the above `lm` formula to work, the `lm(data = )` argument would need to have the competitor info in wide-format. This conversion from `focal_vs_comp` tall-format to lm input wide-format occurs in our hacky `create_bayesian_model_data()` function, found [here](https://github.com/rudeboybert/forestecology/blob/master/R/model_functions.R#L258), used by both our fit and predict functions.

**Comment by simonpcouch** [comment]
Ah, this is super helpful to have noted down! I appreciate you laying this all out.

I'll look to that `create_bayesian_model_data` function as I work through the updated interface.

**Pull request closed without merging**
